# -*- coding: utf-8 -*-
"""automate_ AndiArifAbdillah

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fdq5DgllpeJX_DLICVJOGLIniBvo8Xni
"""

import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import os

def run_preprocessing_pipeline():
    print("Mulai proses otomatisasi preprocessing...")

from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['target'] = iris.target

# Menghapus Duplikat
df_clean = df.drop_duplicates()

# Pemisahan Fitur dan Target
X = df_clean[iris.feature_names]
y = df_clean['target']

# Split Data (Gunakan stratify agar distribusi kelas seimbang)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Standarisasi (Feature Scaling)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

df_final = pd.DataFrame(X_train_scaled, columns=iris.feature_names)
df_final['target'] = y_train.values

# menyimpan hasil preprocessing
output_path = 'iris_preprocessed.csv'
df_final.to_csv(output_path, index=False)

print(f"- Berhasil! Data bersih disimpan di: {output_path}")
print(f"- Jumlah sampel setelah preprocessing: {len(df_final)}")

# Menjalankan fungsi
if __name__ == "__main__":
    run_preprocessing_pipeline()